
name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: self-hosted
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Kill existing a.exe process
      shell: powershell
      run: |
        $process = Get-Process -Name a -ErrorAction SilentlyContinue
        if ($process) {
          Stop-Process -Name a -Force
          echo "a.exe was running and has been terminated."
        } else {
          echo "a.exe not running."
        }
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test1
      id: test1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test1
        setup-command: ''
        command: g++ main.cpp
        timeout: 10
        max-score: 1
    - name: test2
      id: test2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test2
        setup-command: ''
        command: python C:\Users\Public\2025-2\work\week-05\week05-quiz1-01.py main.cpp
        timeout: 10
        max-score: 2

    - name: test3
      id: test3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test3
        setup-command: ''
        command: python C:\Users\Public\2025-2\work\week-05\week05-quiz1-02.py main.cpp
        timeout: 10
        max-score: 2
    
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
      with:

        runners: test1,test2,test3
